Update food_cubit.dart, food_item.dart, food_repo.dart. Rename main.d…
Alexandr019/food pull request #1
Opened 2022-06-30 18:42 UTC by Alexandr019

…art to food_page.dart

2022-07-01 08:55 UTC, Oliinyk-Artemii commented on lib/food_repo.dart
> +    final json = await Dio().get('https://yummly2.p.rapidapi.com/feeds/list',
it's better to have an instance of Dio class in a separate field that we'll initialize in a constructor of FoodRepo

2022-07-01 09:03 UTC, Oliinyk-Artemii requested changes

2022-07-01 09:03 UTC, Oliinyk-Artemii commented on lib/food_cubit.dart
>    final FoodRepo _foodRepo = FoodRepo();
it's better to initialize the fields through the constructor

2022-07-01 09:03 UTC, Oliinyk-Artemii commented on lib/food_page.dart
> +    return MaterialApp(
let's move MaterialApp and main method in main.dart, here we will have only Scaffold for FoodPage

2022-07-02 09:25 UTC, Alexandr019 commented on lib/food_repo.dart
> +    final json = await Dio().get('https://yummly2.p.rapidapi.com/feeds/list',
Done

2022-07-02 09:25 UTC, Alexandr019 commented on lib/food_repo.dart
> +    final json = await Dio().get('https://yummly2.p.rapidapi.com/feeds/list',
Done

2022-07-02 09:25 UTC, Alexandr019 commented on lib/food_item.dart
> +      if (jsonList[i]['content']['details'] != null &&
Done

2022-07-02 09:26 UTC, Alexandr019 commented on lib/food_cubit.dart
>    final FoodRepo _foodRepo = FoodRepo();
Done

2022-07-02 09:26 UTC, Alexandr019 commented on lib/food_page.dart
> +    return MaterialApp(
Done

2022-07-02 14:31 UTC, Oliinyk-Artemii commented on lib/project_router.dart
> +        return _buildRoute(const MyApp());
nope, we need FoodPage here

2022-07-02 14:34 UTC, Oliinyk-Artemii commented on lib/main.dart
> +      routes: {
remove routes and insert
`onGenerateRoute: ProjectRouter.generateRoute,`

2022-07-02 14:35 UTC, Oliinyk-Artemii commented on lib/project_router.dart
> +const _home = '/home';
and change to food

2022-07-02 14:35 UTC, Oliinyk-Artemii commented on lib/project_router.dart
> +const _home = '/home';
const _food = '/food';

2022-07-02 14:56 UTC, Alexandr019 commented on lib/project_router.dart
> +        return _buildRoute(const MyApp());
Done

2022-07-02 14:56 UTC, Alexandr019 commented on lib/main.dart
> +      routes: {
Done

2022-07-02 14:56 UTC, Alexandr019 commented on lib/project_router.dart
> +const _home = '/home';
Done

2022-07-02 19:46 UTC, Oliinyk-Artemii approved these changes

2022-07-03 07:19 UTC, merged