Create details_cubit.dart, details_item.dart, details_page.dart, deta…
Alexandr019/food pull request #2
Opened 2022-07-31 18:37 UTC by Alexandr019

…ils_repo.dart, navigation.dart. Update food_page.dart, main.dart, food_item.dart.

2022-08-08 18:53 UTC, Oliinyk-Artemii requested changes

2022-08-08 18:53 UTC, Oliinyk-Artemii commented on lib/details_cubit.dart
> +class DetailsState {
add equatable lib

2022-08-09 07:35 UTC, Oliinyk-Artemii commented on lib/details_cubit.dart
> +    emit(DetailsState(isLoading: true));
I would implement copyWith method and would change values via this method

2022-08-09 07:37 UTC, Oliinyk-Artemii commented on lib/details_page.dart
> +            Dio(
We need to use DI (dependency injection) here. Remember me plz later, I'll show you how to implement it and why we need this

2022-08-17 18:49 UTC, Alexandr019 commented on lib/details_page.dart
> +            Dio(
done

2022-08-17 18:52 UTC, merged